---
languageCode: ru-ru
baseUrl: https://afonasev.github.io/
title: Afonasev Evgeniy Blog
theme: anubis
paginate: 10
publishDir: "../"
disqusShortname: afonasev
googleAnalytics: UA-123-45
enableRobotsTXT: true
menu:
  main:
  - url: "/posts/"
    name: Archive
    title: Archive
    weight: 1
    identifier: archive
  - url: https://github.com/afonasev
    name: Github
    weight: 2
  - url: mailto:ea.afonasev@gmail.com
    name: Email
    weight: 3
params:
  author: Afonasev Evgeniy Blog
  description: ''
  images:
  - images/og-featured.png
  customCSS:
  - css/my.css
  dateFormat: '2006-01-02'
  paginationSinglePost: false
markup:
  goldmark:
    renderer:
      unsafe: true
