languageCode: "ru-ru"
baseUrl: "https://afonasev.github.io/"
title: "Afonasev Evgeniy Blog"
theme: "anubis"
paginate: 10
publishDir: ../
disqusShortname: afonasev
googleAnalytics: UA-123-45
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

params:
  author: "Afonasev Evgeniy Blog"
  description: ""
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: false

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
