name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.71.1'
        # extended: true

    - name: Build
      run: hugo --minify --environment production

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "action: blog building"
